Adding MapCarbonMessage and SerializableCarbonMessage to Carbon messaging
wso2/carbon-messaging pull request #48
Opened 2017-02-08 10:54 UTC by amjadhifthikar

2017-02-08 11:49 UTC, Kishanthan requested changes

2017-02-08 11:49 UTC, Kishanthan commented on components/src/main/java/org/wso2/carbon/messaging/MapCarbonMessage.java
> +     * To get the value of a particular key
description should end with a period.

2017-02-08 11:49 UTC, Kishanthan commented on components/src/main/java/org/wso2/carbon/messaging/SerializableCarbonMessage.java
> +    public void setHeaders(HashMap<String, String> headers) {
missing java docs for public methods.

2017-02-08 12:09 UTC, Kishanthan approved these changes

2017-02-08 12:09 UTC, merged

2019-04-01 06:01 UTC, amjadhifthikar commented on components/src/main/java/org/wso2/carbon/messaging/MapCarbonMessage.java
> +     * To get the value of a particular key
This is fixed.

2019-04-01 06:01 UTC, amjadhifthikar commented on components/src/main/java/org/wso2/carbon/messaging/SerializableCarbonMessage.java
> +    public void setHeaders(HashMap<String, String> headers) {
This is fixed.